# Generated by Django 4.2.5 on 2023-11-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_like'),
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ManyToManyField(related_name='slider_products', to='product_app.product')),
            ],
        ),
    ]
