# Generated by Django 5.0.6 on 2024-06-23 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_app", "0004_ticket"),
        ("product_app", "0026_product_sold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sliderproducts",
            name="product",
        ),
        migrations.AddField(
            model_name="sliderproducts",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slider_products",
                to="product_app.product",
            ),
        ),
    ]
