# Generated by Django 4.2.5 on 2023-10-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='t_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
