# Generated by Django 4.2.5 on 2023-10-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_product_t_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='t_price',
        ),
        migrations.AddField(
            model_name='product',
            name='after_discount',
            field=models.IntegerField(blank=True, help_text='Dont touch this field pls', null=True),
        ),
    ]
