# Generated by Django 4.2.5 on 2023-10-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_remove_product_after_discount_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
