# Generated by Django 4.2.5 on 2023-11-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='english_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
