# Generated by Django 4.2.5 on 2023-11-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_product_english_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, height_field=718, null=True, upload_to='category_pics', width_field=718),
        ),
    ]
