# Generated by Django 4.2.5 on 2023-11-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0013_productdetail_delete_answer_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='detail',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='answer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='question',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
