# Generated by Django 4.2.5 on 2023-11-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0015_productdetail_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='x',
        ),
    ]
