# Generated by Django 4.2.5 on 2023-11-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0016_remove_productdetail_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
