# Generated by Django 4.2.5 on 2023-11-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0017_product_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='property',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
