# Generated by Django 5.0.6 on 2024-06-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0019_namespace"),
        ("weblog_app", "0024_alter_weblog_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="likee",
            field=models.ManyToManyField(
                related_name="like_products", to="weblog_app.ipmodel"
            ),
        ),
    ]
