# Generated by Django 5.0.6 on 2024-06-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0020_alter_product_likee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="expire_date",
        ),
    ]
