# Generated by Django 5.0.6 on 2024-06-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0021_remove_product_expire_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="product",
            name="likee",
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percentage",
            field=models.SmallIntegerField(
                default=0,
                help_text="if u dont want to discount a price, dont touch this field Tnx :)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="english_title",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=65, unique=True),
        ),
    ]
