# Generated by Django 5.0.6 on 2024-06-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0023_review_delete_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="img/product-pics"),
        ),
    ]
