# Generated by Django 5.0.6 on 2024-06-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0024_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_discounted",
            field=models.BooleanField(default=False),
        ),
    ]
