# Generated by Django 5.0.6 on 2024-06-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0025_product_is_discounted"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sold",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
