# Generated by Django 4.2.5 on 2023-11-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0007_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(),
        ),
    ]
