# Generated by Django 5.0.6 on 2024-06-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0011_cart_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
