# Generated by Django 5.0.6 on 2024-06-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0012_alter_cartitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
