# Generated by Django 4.2.5 on 2023-11-24 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_alter_forgotenpassword_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='expiration_code',
        ),
    ]
