# Generated by Django 4.2.5 on 2023-11-05 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeblogCategroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=20)),
                ('description1', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='img/blog-pics')),
                ('title2', models.CharField(max_length=20)),
                ('description2', models.TextField()),
                ('image2', models.ImageField(blank=True, null=True, upload_to='img/blog-pics')),
                ('title3', models.CharField(max_length=20)),
                ('description3', models.TextField()),
                ('image3', models.ImageField(blank=True, null=True, upload_to='img/blog-pics')),
                ('title4', models.CharField(max_length=20)),
                ('description4', models.TextField()),
                ('image4', models.ImageField(blank=True, null=True, upload_to='img/blog-pics')),
                ('title5', models.CharField(max_length=20)),
                ('description5', models.TextField()),
                ('image5', models.ImageField(blank=True, null=True, upload_to='img/blog-pics')),
                ('conclusion', models.CharField(blank=True, max_length=150, null=True)),
                ('faq1', models.CharField(blank=True, max_length=50, null=True)),
                ('anw1', models.CharField(blank=True, max_length=50, null=True)),
                ('faq2', models.CharField(blank=True, max_length=50, null=True)),
                ('ans2', models.CharField(blank=True, max_length=50, null=True)),
                ('faq3', models.CharField(blank=True, max_length=50, null=True)),
                ('ans3', models.CharField(blank=True, max_length=50, null=True)),
                ('faq4', models.CharField(blank=True, max_length=50, null=True)),
                ('ans4', models.CharField(blank=True, max_length=50, null=True)),
                ('faq5', models.CharField(blank=True, max_length=50, null=True)),
                ('ans5', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study_time', models.IntegerField(default=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weblog', to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(related_name='categories', to='weblog_app.weblogcategroy')),
            ],
        ),
    ]
