# Generated by Django 4.2.5 on 2023-11-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='main_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
