# Generated by Django 4.2.5 on 2023-11-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0002_weblog_main_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weblog',
            old_name='anw1',
            new_name='ans1',
        ),
    ]
