# Generated by Django 4.2.5 on 2023-11-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0003_rename_anw1_weblog_ans1'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/blog-pics'),
        ),
        migrations.AddField(
            model_name='weblog',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
    ]
