# Generated by Django 4.2.5 on 2023-11-05 20:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0006_weblog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
