# Generated by Django 4.2.5 on 2023-11-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0008_remove_weblog_ans1_remove_weblog_ans2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='weblog_app.weblogcategroy'),
        ),
    ]
