# Generated by Django 4.2.5 on 2023-11-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0010_weblogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblogcomment',
            name='body',
            field=models.TextField(default='None'),
        ),
    ]
