# Generated by Django 4.2.5 on 2023-11-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0012_alter_weblog_main_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblog',
            name='main_title',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
