# Generated by Django 4.2.5 on 2023-11-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0015_ipmodel_weblog_tags_weblog_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
