# Generated by Django 4.2.5 on 2023-11-10 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weblog_app', '0016_weblog_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeblogVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=50)),
                ('main_picture', models.ImageField(upload_to='img/')),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='weblog-video/')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weblog_video', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
