# Generated by Django 4.2.5 on 2023-11-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0019_weblogvideo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblogcomment',
            name='study_time',
            field=models.IntegerField(default=5),
        ),
    ]
