# Generated by Django 4.2.5 on 2023-11-10 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0021_remove_weblogcomment_study_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblogvideocomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_video_comments', to='weblog_app.weblogvideo'),
        ),
    ]
