# Generated by Django 4.2.5 on 2023-11-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_app', '0022_alter_weblogvideocomment_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weblogvideo',
            name='main_picture',
        ),
        migrations.AddField(
            model_name='weblogvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='img/thumbnails'),
        ),
    ]
